document.write(`
<p style="font-size:20px" align="justify">
I believe that potential is infinite. When it comes to my students, it doesn't matter where they come from, what class they were born into, what privilege they have or they lack. The goal is growth, plain and simple. As a teacher, it's my job to be sure that not only are my students proficient in the material they are tasked to cover, but that they strive for the greatest of growth which they can manage. For some, growth is second nature. For those students, the responsibility is to be sure that the requisite assistance and material is available for them to strive. For others, sometimes growth takes a bit of work. For these students, the responsibility I assume as their mentor is to go beyond the call of duty and work unremittingly in partnership to see them achieve their best. 
<br><br>
There's a dichotomy here that I find to be one of the the greatest challenges when it comes to education: maintaining the standard that every individual student has an equality of opportunity for success, but recognizing the truth that support needs to be dispropotionally allocated towards those who most need it. This reality is a particular challenge at the undergraduate level, where for these college students so much of their path has already been defined. Nevertheless, our job as educators and mentors isn't to shy away from the challenges which we find difficult. It is to see the situation as it is, but also see what it can become. It's to strive towards infinite potentials with great enthusiasms and devotion to student success. President Roosevelt once said, "credit belongs to the man who is actually in the arena... who knows great enthusiasms, the great devotions; who spends himself in a worthy cause; who at the best knows in the end the triumph of high achievement, and who at the worst, if he fails, at least fails while daring greatly." This vision of daring greatly is the same vision which brought me from being the one to whom growth took a bit of work, to where I am today. And through my experience in the years which I have been studying and teaching, I've come to truly believe that great enthusiasms and great devotions, coupled with logical and intelligent approach, are the key to bringing forth from potentiality the results which we so dare greatly to realize.
<br><br>
When it comes to manifesting growth in the classroom, I like do draw on my experience both as a student of chemistry, as well as a student of programming. One of the core tennants of the Python programming language is 'explicit is better than implicit.' And, some of the best chemistry professors who I have studied under, such as Dr. Eric Brauns at the University of Idaho and Dr. Charles Wurrey at the University of Missouri-Kansas City, have all managed to adhere to this ideal in their teaching. I aspire to do the same. To me, this means not leaving room for guesswork in lecture material. Full derivations, full context, and A depth-first approach to content. If necessary to choose, I would rather teach students <i>how</i> truth is derived, not <i>what</i> truth is. Only one of these models scales beyond the classroom, and our job as educators is to prepare students for life beyond university education.
<br><br>
Finally, there's something to be said about conducting yourself in a manner which is beyond mere content. I don't see teaching as a sort of seminar setting where there's the person at the front who knows the material, and the task is to regurgitate the information to those who don't. No, there's more nuance to it than that. It's more of a discussion - more a dialogue - between the teacher and students. There's a reciprocity to the experience. Not only are students tasked from learning from the material I teach, but I in turn am tasked to learn from the students, both observing how they respond to the material in real-time, and tuning the lecture performance towards that to which the audience best resonates. In this way, teaching is more of an art than a science. From my experience as a student, the best teachers have always been able to convey their content at a level beyond mere information transfer. Granted, there's a certain <i>je ne sais quoi</i> to it - I can't exactly describe it. But, I know what it is. I've seen it. Experienced it. And I do my best to teach it.
<br><br>
So in terms of a teaching philosophy, here's my aim: Work with students at an individual level; provide explicit standards and guidance as to how they can achieve growth which scales; recognize that different students require different styles and levels of engagement to achieve high-yield; tailor the education experience to meet students where they are at, in a manner which inspires the greatest growth.
</p>
`)